# LOGIN PAGE
mobileInput=//input[@type='tel']
termsCheckbox=//input[@type='checkbox']
continueBtn=//div[text()='CONTINUE']

# HOME PAGE
popupClose=//span[contains(@class,'desktop-iconClose')]
menTab=//a[contains(@href,'/shop/men')]
topwearMenu=//a[text()='Topwear']


# Category
jacketCategory=//label[contains(.,'Jackets')]

# Brand section
brandSection=//span[text()='Brand']
#brandSection=//div[contains(text(),'Brand')]
pumaBrand=//label[contains(.,'Puma')]
roadsterBrand=//label[contains(.,'Roadster')]

# PRODUCT LIST PAGE
firstProduct=(//li[contains(@class,'product-base')]//a)[1]

# PRODUCT PAGE
sizeXXL=//p[text()='XXL']/parent::button[not(@disabled)]
availableSizes=//div[contains(@class,'size-buttons')]//button[not(@disabled)]
addToBagBtn=//div[contains(text(),'ADD TO BAG')]
goToBagPopupBtn=//a[contains(@class,'goToCart')]

# CART PAGE
placeOrderBtn=//div[contains(text(),'PLACE ORDER')] | //span[contains(text(),'PLACE ORDER')]
